// <auto-generated />
using System;
using BookapiMinimal.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookapiMinimal.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookapi")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookapiMinimal.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", "bookapi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30554fd5-7186-4f52-a271-9eabc88594bb"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("bcd324dd-c3ea-4f98-9e80-5766113255f1"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("43017ca4-6f0e-4039-9e26-9a1f95ba76d3"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("bbf2c501-8156-424c-80f4-b09e1e3dd445"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("b1d0b271-0c9d-4c23-b42c-dbff63aa8c45"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("c7851419-7437-45fd-ac8f-657574aa5a31"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
